# Snakefile to run Amdahl's Law for HPC Workflows

TASKS = range(1, 32)  # number of processors: start small for testing!

rule plot:
    input:
        expand("amdahl_np{task}.json", task=TASKS)
    output:
        "plot.log"
    log:
        "slurm_plot.log"
    resources:
        tasks=1
    conda:
        "amdahl"
    shell:
        "python3 plot_amdahl.py > {output}"

rule amdahl:
    input:
    output:
        "amdahl_np{sample}.json"
    log:
        "slurm_np{sample}.out"
    resources:
        tasks=lambda wildcards: int(wildcards.sample)
    shell:
        "mpirun amdahl --terse > {output}"

rule clean:
    input:
    output:
    resources:
        tasks=1
    conda:
        "amdahl"
    shell:
        "rm *.log *.json *.png"
