import glob
import os


DATS_DIR = 'dats'
DATS = expand('{dir}/{file}.dat', dir=DATS_DIR, file=glob_wildcards('./books/{book}.txt').book)


# Generate summary table
rule zipf_test:
    input:
        cmd='zipf_test.py',
        dats=DATS
    output: 'results.txt'
    shell:  'python {input.cmd} {input.dats} > {output}'

rule dats:
    input: DATS

# delete everything so we can re-run things
rule clean:
    shell: 'rm -rf {DATS_DIR} *.dat results.txt'

# Count words in one of the books
rule count_words:
    input:
        cmd='wordcount.py',
        book='books/{file}.txt'
    output: '{DATS_DIR}/{file}.dat'
    shell: 'python {input.cmd} {input.book} {output}'

rule print_book_names:
    run:
        print('These are all the book names:')
        for book in glob.glob('books/*.txt'):
            print(book)