# Generate summary table
rule zipf_test:
    input:  'zipf_test.py', 'isles.dat', 'abyss.dat', 'last.dat'
    output: 'results.txt'
    shell:  'python {input[0]} {input[1]} {input[2]} {input[3]} > {output}'

rule dats:
    input: 'isles.dat', 'abyss.dat', 'last.dat'

# delete everything so we can re-run things
rule clean:
    shell: 'rm -f *.dat results.txt'

# Count words in one of the books
rule count_words:
    input:
        cmd='wordcount.py',
        book='books/{file}.txt'
    output: '{file}.dat'
    shell: 'python {input.wc} {input.book} {output}'
